config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get "today" => "days#today", as: "today"
  get "queue" => "days#queue", as: "queue"

  get "log_out" => "sessions#destroy", as: "log_out"
  get "log_in" => "sessions#new", as: "log_in"
  get "sign_up" => "users#new", as: "sign_up"

  get '/e/:id' => 'entries#find', as: 'find_entry'
  get '/stories/new' => 'submissions#new_story', as: 'new_story'

  root to: "home#index"
  get "archive" => "home#archive", as: "archive"
  get "about" => "home#about", as: "about"

  resources :days
  resources :users
  resources :sessions
  resources :entries

  resources :submissions do
    post '/assign' => 'submissions#assign', as: 'assign'
  end

  post '/create_and_publish' => 'submissions#create_and_publish', as: 'create_and_publish'

  resources :stories do
    post '/toggle_status' => 'stories#toggle_status', as: 'toggle_status'
  end

end

app/models/entry.rb
# == Schema Information
#
# Table name: entries
#
#  id          :integer          not null, primary key
#  parent_id   :integer
#  parent_type :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer
#  text        :string(255)
#  ending      :boolean
#

class Entry < ActiveRecord::Base
  obfuscate_id

  self.per_page = 5

  belongs_to :story
  belongs_to :user

  belongs_to :parent, polymorphic: true
  has_many :entries, as: :parent, dependent: :destroy

  accepts_nested_attributes_for :parent

  validates :parent, presence: true
  validates :text, presence: true
  validate :user_cannot_write_consecutive_sentences
  validate :entry_text_is_only_one_sentence

  attr_accessor :override_sentence_limit

  def story
    if parent_type == 'Story'
      parent
    elsif parent.present?
      parent.story
    else
      nil
    end
  end

  def first_sentence?
    parent_type == 'Story'
  end

  def descendants
    entries.flat_map { |e| [e] + e.descendants }
  end

  def leaves
    descendants.select { |e| e.leaf? }
  end

  def leaf?
    entries.empty?
  end


  private

  def user_cannot_write_consecutive_sentences
    if parent_type == 'Entry' && parent.user == self.user
      errors.add(:base, "Can't contribute two sentences in a row")
    end
  end

  def entry_text_is_only_one_sentence
    unless override_sentence_limit || text.blank? #the other validation will catch blank text
      tokenizer = Punkt::SentenceTokenizer.new(text)
      result    = tokenizer.sentences_from_text(text, :output => :sentences_text)
      if result.reject { |s| s.length <= 1 }.size > 1
        errors.add(:base, "Entries must be made up of one sentence only")
      end
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :allow_story_creation, only: :new
  before_filter :authorize, only: :destroy

  def new
    @new_entry = Entry.new(story: Story.new)
  end

  def create
    @entry = Entry.create(entry_params.merge(user: current_user))
    @entry.build_story if params[:parent_type] == 'Story'

    if @entry.save
      attempt_closing_story(@entry.story)
      attempt_wrapping_story(@entry.story)
      redirect_to entry_path(@entry)
    else
      if @entry.parent.new_record?
        flash[:error] = @entry.errors.to_a.join(", ")
        redirect_to new_entry_path
      else
        redirect_to @entry.parent
      end
    end
  end

  def show
    encoded = Base58.encode(params[:id].to_i)
    redirect_to find_entry_path(@entry, {id: encoded, delete: params[:delete]})
  end

  def find
    Rails.logger.info("locating entry #{params[:id]}")
    decoded = Base58.decode(params[:id])
    @entry = Entry.find(decoded)

    @entry.story.close_public_if_ready

    edits_allowed = @entry.story.can_be_edited?(current_user)
    delete_mode = edits_allowed & !!params[:delete].present?

    if @entry.nil?
      raise ActiveRecord::RecordNotFound
    elsif can_show_story || delete_mode
      leaf = @entry.leaf? ? @entry : @entry.leaves.sample
      @story = leaf.story
      @entries = @story.paths(leaf).first
      render('read', locals: {delete_mode: delete_mode}) and return
    end

    leaves = @entry.leaves

    #filter out paths where the current user is ineligible to add a sentence
    #(most likely because they wrote the last sentence)
    if current_user
      eligible_leaves = leaves.select { |leaf| leaf.user != current_user }
      leaves = eligible_leaves unless eligible_leaves.blank?
    end

    @entry = leaf_with_shortest_path(leaves, @entry.story) unless @entry.leaf?

    @new_entry = @entry.entries.build
    @new_entry.ending = true if @entry.story.wrapping?
    @entries = @entry.story.paths(@entry).first
    @entries.pop(2) #remove the one we're showing & the one we're writing

    render 'contribute'
  end

  def destroy
    @entry = Entry.find(params[:id])

    user_can_destroy = @entry.story.can_be_edited?(current_user)
    user_owns_entry = current_user && @entry.user == current_user

    if user_can_destroy || user_owns_entry
      entry_parent = @entry.parent
      @entry.destroy
      flash[:message] = 'Entry deleted.'
    else
      flash[:error] = 'Unauthorized action!'
    end

    redirect_to entry_path(entry_parent)
  end

  private

  def can_show_story
    @entry.story.closed?
  end

  def entry_params
    params.require(:entry).permit(:text, :parent_type, :parent_id, parent_attributes: [ :id, :title ])
  end

  def attempt_closing_story(story)
    unfinished_leaves = story.leaves.select { |e| e.ending = false }
    story.update(status: "closed") if story.wrapping? && unfinished_leaves.empty?
  end

  def attempt_wrapping_story(story)
    story.update(status: "wrapping") if story.ready_to_wrap?
  end

  def leaf_with_shortest_path(leaves, story)
    leaves.inject({}) { |m,k| m.update(k => story.paths(k).first.size) }
          .min_by(&:last).first
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def entry_date(e)
    e.created_at.strftime("%A, %B %e %Y")
  end

  def fake_entry_text(length)
    "%-10s" % FAKE_TEXT.split(".").sample.truncate(length)
  end

  def random_sentence_end_mark
    ("." * 20 << "!" << "?").split("").sample
  end

  def attribution_text(entry)
    if current_user && entry.user == current_user
      'you'
    elsif entry.user.present?
      entry.user.display_name
    else
      'Anonymous'
    end
  end

  FAKE_TEXT =
<<-EULA
  END-USER LICENSE AGREEMENT FOR MICROSOFT SOFTWARE

  MICROSOFT WINDOWS INSTALLER VERSION 31

  IMPORTANT—READ CAREFULLY: This End-User License Agreement (“EULA”) is a legal agreement between you (either an individual or a single entity) and Microsoft Corporation (“Microsoft”) for the Microsoft software that accompanies this EULA, which includes computer software and may include associated media, printed materials, “online” or electronic documentation, and Internet-based services (“Software”).  An amendment or addendum to this EULA may accompany the Software.  YOU AGREE TO BE BOUND BY THE TERMS OF THIS EULA BY INSTALLING, COPYING, OR OTHERWISE USING THE SOFTWARE. IF YOU DO NOT AGREE, DO NOT INSTALL, COPY, OR USE THE SOFTWARE; YOU MAY RETURN IT TO YOUR PLACE OF PURCHASE (IF APPLICABLE) FOR A FULL REFUND.

  1	GRANT OF LICENSE.  Microsoft grants you the following rights provided that you comply with all terms and conditions of this EULA:  You may install and use the Software on a single computer solely for the purpose of designing, developing, and testing applications for use with Microsoft Windows 2000 Service Pack 3, Windows 2000 Service Pack 4, Windows XP, Windows XP Service Pack 1, Windows Server 2003 and Windows XP Service Pack 2.  You may not use the Software to create files which are not compatible with the Microsoft Windows Installer file format. 
  11	Documentation.  You may make and use an unlimited number of copies of any documentation, provided that such copies shall be used only for personal purposes and are not to be republished or distributed (either in hard copy or electronic form) beyond your premises.
  12	Storage/Network Use. You may also store or install a copy of the Software on a storage device, such as a network server, used only to install or run the Software on computers used by a licensed end user in accordance with Section 11.  A single license for the Software may not be shared or used concurrently by multiple end users.
  2	ADDITIONAL LICENSE RIGHTS -- REDISTRIBUTABLE CODE.  In addition to the rights granted in Section 1, certain portions of the Software, as described in this Section 2, are provided to you with additional license rights.  These additional license rights are conditioned upon your compliance with the distribution requirements and license restrictions described in Section 3.
  21	Sample Code. Microsoft grants you the right to: (a) use and modify the source code version of those portions of the Software identified as “Samples” in REDIST.TXT or elsewhere in the Software (“Sample Code”) for the sole purposes of designing, developing, and testing your Software(s), and (b) a limited, nonexclusive, royalty-free right to reproduce and distribute the Sample Code, along with any modifications thereof, in object and/or source code form.  For applicable redistribution requirements for Sample Code, see Section 3 below.
  22	Redistributable Code. Microsoft grants you a nonexclusive, royalty-free right to reproduce and distribute the object code form of any portion of the Software listed in REDIST.TXT (“Redistributable Code”).  For general redistribution requirements for Redistributable Code, see Section 3, below.  
  3	DISTRIBUTION REQUIREMENTS AND OTHER LICENSE RIGHTS AND LIMITATIONS.  If you choose to exercise your rights under Section 2, any redistribution by you is subject to your compliance with Section 3.
  31	General Distribution Requirements.  
  (a)	If you choose to redistribute Sample Code, or Redistributable Code (collectively, the “Redistributables”) as described in Section 2, you agree:  (i) except as otherwise noted in Section 2.1 (Sample Code), to distribute the Redistributables only in object code form and in conjunction with and as a part of a software application product developed by you that adds significant and primary functionality to the Redistributables (“Licensee Software”); (ii) that the Redistributables only operate in conjunction with Microsoft Windows platforms and ) the application does not allow the use of the Redistributables for files which are not compatible with the Microsoft Windows Installer; (iii) the library code in the LIB directory may only be redistributed when linked into your application; (iv) that if the Licensee Software is distributed beyond Licensee’s premises or externally from Licensee’s organization, to distribute the Licensee Software containing the Redistributables pursuant to an end user license agreement (which may be “break-the-seal”, “click-wrap” or signed), with terms no less protective than those contained in this EULA; (v) not to use Microsoft’s name, logo, or trademarks to market the Licensee Software; (vi) to display your own valid copyright notice which shall be sufficient to protect Microsoft’s copyright in the Software; (vii) not to remove or obscure any copyright, trademark or patent notices that appear on the Software as delivered to you; (viii) to indemnify, hold harmless, and defend Microsoft from and against any claims or lawsuits, including attorney’s fees, that arise or result from the use or distribution of the Licensee Software; (ix) to otherwise comply with the terms of this EULA; and (x) agree that Microsoft reserves all rights not expressly granted.  
  You also agree not to permit further distribution of the Redistributables by your end users except you may permit further redistribution of the Redistributables by your distributors to your end-user customers if your distributors only distribute the Redistributables in conjunction with, and as part of, the Licensee Software, you comply with all other terms of this EULA, and your distributors comply with all restrictions of this EULA that are applicable to you. 
  (b)	If you use the Redistributables, then in addition to your compliance with the applicable distribution requirements described for the Redistributables, the following also applies.  Your license rights to the Redistributables are conditioned upon your not (i) creating derivative works of the Redistributables in any manner that would cause the Redistributables in whole or in part to become subject to any of the terms of an Excluded License; or (ii) distributing the Redistributables (or derivative works thereof) in any manner that would cause the Redistributables to become subject to any of the terms of an Excluded License.  An “Excluded License” is any license that requires as a condition of use, modification and/or distribution of software subject to the Excluded License, that such software or other software combined and/or distributed with such software be (x) disclosed or distributed in source code form; (y) licensed for the purpose of making derivative works; or (z) redistributable at no charge.
  4	RESERVATION OF RIGHTS AND OWNERSHIP.  Microsoft reserves all rights not expressly granted to you in this EULA.  The Software is protected by copyright and other intellectual property laws and treaties. Microsoft or its suppliers own the title, copyright, and other intellectual property rights in the Software.  The Software is licensed, not sold.
  5	LIMITATIONS ON REVERSE ENGINEERING, DECOMPILATION, AND DISASSEMBLY.  You may not reverse engineer, decompile, or disassemble the Software, except and only to the extent that such activity is expressly permitted by applicable law notwithstanding this limitation.
  6	NO RENTAL/COMMERCIAL HOSTING. You may not rent, lease, lend or provide commercial hosting services with the Software.
  7	CONSENT TO USE OF DATA.  You agree that Microsoft and its affiliates may collect and use technical information gathered as part of the product support services provided to you, if any, related to the Software.  Microsoft may use this information solely to improve our products or to provide customized services or technologies to you and will not disclose this information in a form that personally identifies you.   
  8	LINKS TO THIRD PARTY SITES.  You may link to third party sites through the use of the Software.  The third party sites are not under the control of Microsoft, and Microsoft is not responsible for the contents of any third party sites, any links contained in third party sites, or any changes or updates to third party sites.  Microsoft is not responsible for webcasting or any other form of transmission received from any third party sites.  Microsoft is providing these links to third party sites to you only as a convenience, and the inclusion of any link does not imply an endorsement by Microsoft of the third party site.
  9	ADDITIONAL SOFTWARE/SERVICES.  This EULA applies to updates, supplements, add-on components, or Internet-based services components, of the Software that Microsoft may provide to you or make available to you after the date you obtain your initial copy of the Software, unless we provide other terms along with the update, supplement, add-on component, or Internet-based services component.  Microsoft reserves the right to discontinue any Internet-based services provided to you or made available to you through the use of the Software.  
  10	NOT FOR RESALE SOFTWARE.  Software identified as “Not For Resale” or “NFR,” may not be sold or otherwise transferred for value, or used for any purpose other than demonstration, test or evaluation.

app/views/entries/_form.html.erb
<% guidance = local_assigns[:guidance] || 'Your entry' %>
<%= form_for @new_entry, html: { class: "new-entry" } do |f| %>
  <% if @new_entry.errors.any? %>
    <% @new_entry.errors.full_messages.each do |msg| %>
      <div><%= "Error: #{msg} " %></div>
    <% end %>
  <% end %>

  <%= f.hidden_field :parent_type %>
  <%= f.hidden_field :parent_id %>

  <% if @new_entry.parent.new_record? %>
    <%= f.fields_for :parent do |sf| %>
      <p>
        <%= sf.label :title, "Title (optional)" %>
        <%= sf.text_field :title, autofocus: @new_entry.parent.new_record? %>
      </p>
    <% end %>
  <% end %>

  <p>
    <%= f.label :text, guidance, class: "guidance" %>
    <%= f.text_area :text, autofocus: @new_entry.parent.persisted? %>
  </p>

  <p class="submit-entry">
    <%= f.submit 'Submit', class: "submit-entry-button" %>
  </p>
<% end %>

app/views/entries/contribute.html.erb
<h2 class="title">
  <% if @entry.story.title.present? %>
    <%= @entry.story.title %>
  <% else %>
    Untitled
  <% end %>
</h2>

<div class="guidance">
  <% if @entries.empty? %>
    <% if current_user %>
      The story begins here:
    <% else %>
      What follows is the first sentence in a story.
      Read it and consider what the next sentence would be,
      then log in to add it so the game can begin!
    <% end %>
  <% else %>
    <% if current_user %>
      The story so far:
    <% else %>
      The following is a story, but you can't read it
      until you've contributed to it! Take a look at
      the last sentence written and log in to add your
      own&mdash;only then will the full story be revealed...
    <% end %>
  <% end %>
</div>

<div class="current-story">
  <% @entries.each do |e| %>
    <span class="hidden-entry">
      <%= fake_entry_text(e.text.length) %>
    </span>
    <%= random_sentence_end_mark %>
  <% end %>


  <span class="entry-text">
    <%= @entry.text %>
  </span>
</div>

<hr class="faded">


<% if current_user %>
  <% if @entry.user == current_user %>
    <div class="guidance">
      You wrote the last sentence in this story! Unfortunately that means you
      can't add more just yet. Send your friends to the story ASAP to get the
      ball rolling again!
    </div>
  <% else %>
    <div class="entry-submission">
      <%
        guidance = 'Continue the story with one new sentence.'
        if @entry.story.wrapping?
          guidance += 'This is the final sentence in this story path! Try to wrap it up as best you can.'
        end
      %>
      <%= render 'form', guidance: guidance %>
    </div>
  <% end %>
<% else %>
  <div class="guidance">
    Ready to write the next sentence?
  </div>
  <div class="call-to-login">
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %> first!
  </div>
<% end %>

app/views/entries/new.html.erb
<hr class="faded">

<div class="entry-submission">
  <%= render 'form', guidance: 'Let the story begin!' %>
</div>

app/views/entries/read.html.erb
<% delete_mode ||= false %>

<% if @story.title.present? %>
  <h2 id="title"><%= @story.title %></h2>
<% end %>

<div class="story-text">
  <% @entries.each do |e| %>
    <span class="entry <%= 'yours' if e.user == current_user %>">
      <%= link_to_if delete_mode, e.text, entry_path(e), method: :delete %>
    </span>
<% end %>
</div>

<hr class="faded">

<div class="wat">
  <% if @story.closed? && @story.contributed?(current_user) %>
    <p>
      The preceding was a story you participated in on
      <%= entry_date(@story.contributions_from(current_user).first) %>.
      <% case @entries.map(&:user).count(current_user) %>
        <% when 0 %>
        This particular path didn't include your sentence;
          <%= link_to "click here", @story.contribution_from(current_user) %>
          to see a path that includes yours.
        <% when 1 %>
          The sentence in bold is yours.
        <% else %>
          The sentences in bold are yours.
      <% end %>
    </p>
    <% unless @story.closed? %>
      <p>
        This story is still open for contributions. Share this page
        with your friends and they'll have a chance to contribute their
        own sentence, or come back later to add a sentence once more have been
        added!
      </p>
    <% end %>
    <% if @story.can_be_edited?(current_user) %>
      <p>
        <% if @story.closed? %>
          This story has been closed by an admin or the story's creator.
          <% unless @story.stale_public_story? %>
            <%= link_to "Click here", story_toggle_status_path(@story), method: :post %> to open it.
          <% end %>
        <% else %>
          As an admin or the creator of this story, you may
          <%= link_to "close it", story_toggle_status_path(@story), method: :post %>
          to end contributions.
        <% end %>
        <% if delete_mode %>
          You are currently in DELETE MODE.
          <%= link_to "Click here", entry_path(@entries.last) %> to exit it.
        <% elsif current_user && current_user.admin? %>
          You have permission to delete entries from this story if necessary.
          <%= link_to "Click here", entry_path(@entries.last, params: {delete: true}) %>
          to switch to DELETE MODE.
        <% end %>
      </p>
    <% end %>
  <% else %>
    The preceding was a story written by Narratron community members
    <% if @entries.first.created_at.to_date == @entries.last.created_at.to_date %>
      on <%= entry_date(@entries.first) %>
    <% else %>
      between <%= entry_date(@entries.first) %>
      and <%= entry_date(@entries.last) %>
    <% end %>
    <% unless current_user %>
      <div class="call-to-login">
        <%= link_to "Sign up", sign_up_path %> or
        <%= link_to "log in", log_in_path %> 
        to contribute to a story today!
      </div>
    <% end %>
  <% end %>
</div>

<hr class="faded">

<div class="story-credits">
  <p>
  <% if @story.thanks.present? %>
    <% @entries.shift %>
    Story prompt by <%= @story.thanks %>.
  <% end %>
  <% unless @entries.empty? %>
    Sentences in this story path were contributed by
    <%= @entries.map { |e| attribution_text(e) }.to_sentence %>.
  <% end %>
  </p>
</div>

app/views/entries/show.html.erb
<div class="entry-text">
  <%= @entry.text %>
</div>

<div class="guidance">
  Continue the story with one new sentence
</div>

<% if current_user then %>
    <div class="entry-submission">
      <%= render 'form' %>
    </div>
<% else %>
  <div class="call-to-login">
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %> first!
  </div>
<% end %>