config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get "today" => "days#today", as: "today"
  get "queue" => "days#queue", as: "queue"

  get "log_out" => "sessions#destroy", as: "log_out"
  get "log_in" => "sessions#new", as: "log_in"
  get "sign_up" => "users#new", as: "sign_up"

  get '/e/:id' => 'entries#find', as: 'find_entry'
  get '/stories/new' => 'submissions#new_story', as: 'new_story'

  root to: "home#index"
  get "archive" => "home#archive", as: "archive"
  get "about" => "home#about", as: "about"

  resources :days
  resources :users
  resources :sessions
  resources :entries

  resources :submissions do
    post '/assign' => 'submissions#assign', as: 'assign'
  end

  post '/create_and_publish' => 'submissions#create_and_publish', as: 'create_and_publish'

  resources :stories do
    post '/toggle_status' => 'stories#toggle_status', as: 'toggle_status'
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  email         :string(255)
#  display_name  :string(255)
#  password_hash :string(255)
#  password_salt :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  admin         :boolean
#

class User < ActiveRecord::Base
  obfuscate_id

  attr_accessor :password
  before_save :encrypt_password
  before_save :downcase_email

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_presence_of :display_name
  validates_uniqueness_of :email, case_sensitive: false

  has_many :entries, dependent: :destroy
  has_many :favorites
  has_many :stories, through: :entry

  def self.authenticate(email, password)
    user = find_by_email(email.downcase)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def downcase_email
    self.email = self.email.downcase
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_after_filter :store_return_to

  def new
    @user = User.new
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:message] = "Details updated!"
      redirect_back_or_default(user_path(@user))
    else
      render "edit"
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      cookies.permanent.signed[:user_id] = @user.id
      flash[:message] = "Signed up!"
      redirect_back_or_default(root_url)
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
    @updating = true
    @user.password = ''
  end

  def show
    @user = User.find(params[:id])
    @contributions = Entry.where(user: @user)
                          .paginate(page: params[:page])
                          .order('created_at DESC')

    if current_user && (current_user.admin? || current_user == @user)
      render 'show'
    else
      flash[:error] == 'User profiles are currently private.'
      redirect_back_or_default(root_path)
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :display_name, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_form_submit_button_text(user = nil)
    if current_user
      "Update#{' your' if current_user == user} profile"
    else
      "Sign up"
    end
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :display_name %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= "(leave blank if unchanged)" if @updating %>
    <br />
    <%= f.password_field :password, autocomplete: ('off' if @updating)%>
  </p>
  <p>
  <%= f.label :password_confirmation %>
  <%= "(leave blank if unchanged)" if @updating %>
  <br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit user_form_submit_button_text(f.object) %></p>
<% end %>

app/views/users/edit.html.erb
<h1> Edit Info</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field: display_name %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<h2>
  <%= @user.display_name %>
</h2>

<p class="actions">
  <%= link_to "Edit Info", edit_user_path(@user) %>
</p>

<% if @contributions.present? %>
  <h3>
    Contributions
    <span class="contribution-count">
      <%= @user.entries.size %>
    </span>
  </h3>

  <div id="contributed-stories">
    <% @contributions.each do |e| %>
      <blockquote class="user-profile-entry">
        <p><%= e.text %></p>
      </blockquote>

      <div class="story-link">
        <%= link_to "View Story", entry_path(e) %>
      </div>

    <% end %>
  </div>

  <%= will_paginate @contributions, page_links: false %>
<% else %>
  <p>
    <strong>You haven&rsquo;t contributed to any stories yet.</strong>
    You should join <%= link_to "today&rsquo;s public story".html_safe, today_path %>!
  </p>
<% end %>