config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get "today" => "days#today", as: "today"
  get "queue" => "days#queue", as: "queue"

  get "log_out" => "sessions#destroy", as: "log_out"
  get "log_in" => "sessions#new", as: "log_in"
  get "sign_up" => "users#new", as: "sign_up"

  get '/e/:id' => 'entries#find', as: 'find_entry'
  get '/stories/new' => 'submissions#new_story', as: 'new_story'

  root to: "home#index"
  get "archive" => "home#archive", as: "archive"
  get "about" => "home#about", as: "about"

  resources :days
  resources :users
  resources :sessions
  resources :entries

  resources :submissions do
    post '/assign' => 'submissions#assign', as: 'assign'
  end

  post '/create_and_publish' => 'submissions#create_and_publish', as: 'create_and_publish'

  resources :stories do
    post '/toggle_status' => 'stories#toggle_status', as: 'toggle_status'
  end

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  self.per_page = 10

  validates :text, presence: true
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_filter :authorize, except: [:new, :create]

  def index
    @submissions = Submission.paginate(page: params[:page]).order('created_at DESC')
    next_twenty_days = (0..19).map { |x| (Day.pacific_time + x.days).to_date }
    @unassigned_days = next_twenty_days.reject { |d| Day.exists?(date: d) }
  end

  def new
    @submission = Submission.new
  end

  def new_story
    @submission = Submission.new
    @publish_now = true

    render :new
  end

  def create_and_publish
    @submission = Submission.new(submission_params)

    story = Story.new(thanks: @submission.author, title: @submission.title)
    entry = Entry.new(text: @submission.text, parent: story,
                      override_sentence_limit: true, user: current_user)
    unless story.save && entry.save
      flash[:error] = entry.errors.to_a.join(", ")
      redirect_to create_story_path and return
    end

    flash[:message] = "Story created!"
    redirect_to entry_path(entry)
  end

  def create
    @submission = Submission.new(submission_params)

    flash[:message] = "Submission received! Thanks, friend." if @submission.save
    redirect_to new_submission_path
  end

  def assign
    params.permit(:date)
    submission = Submission.find(params[:submission_id])

    story = Story.new(thanks: submission.author)
    entry = Entry.new(text: submission.text, parent: story, override_sentence_limit: true)
    unless story.save && entry.save
      flash[:error] = entry.errors.to_a.join(", ")
      redirect_to submissions_path and return
    end

    params.permit(:date)
    if day = Day.create(date: Date.parse(params[:date]), story: story)
      submission.destroy
      flash[:message] = "Submission queued for #{day.date.strftime('%A %d %b')}"
    end

    if Submission.any?
      redirect_to submissions_path
    else
      redirect_to queue_path
    end

  end

  def destroy
    @submission = Submission.find(params[:id])
    flash[:message] = "Submission deleted!" if @submission.destroy
    redirect_back_or_default(submissions_path)
  end

  private

  def submission_params
    params.require(:submission).permit(:id, :text, :title, :author)
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/index.html.erb
<h2>Pending submissions</h2>

<% @submissions.each do |submission| %>
  <div class="pending-submission">
    <h3 class="submission-title"><%= submission.title || "Untitled" %></h3>
    <p class="submission-text"><%= submission.text %></p>
    <p class="submission-author"><%= submission.author %></p>
    <ul class="submission-actions">
      <li>
        <form action="<%= submission_assign_path(submission) %>" method="post">
          <input name="authenticity_token" value="<%= form_authenticity_token %>"
            type="hidden">
          <label>Assign to date: </label>
          <input type="submit" value="Do it"/>
          <select name="date">
            <% @unassigned_days.each do |day| %>
              <option value="<%= day.strftime("%Y%m%d") %>">
                <%= day.strftime("%A %d %b") %>
              </option>
            <% end %>
          </select>
        </form>
      <li><%= link_to "delete", submission_path(submission), method: :delete %>
    </ul>
  </div>
<% end %>

<%= will_paginate @submissions, page_links: false %>

app/views/submissions/new.html.erb
<% @publish_now ||= false %>

<%= form_for @submission, url: @publish_now ? create_and_publish_path : submission_create_path(@submission),
        html: { class: "new-submission" } do |f| %>

  <% if @submission.errors.any? %>
    <% @submission.errors.full_messages.each do |msg| %>
      <div><%= "Error: #{msg} " %></div>
    <% end %>
  <% end %>

  <%= f.hidden_field :id %>

  <p>
    <%= f.label :title, "Title (optional)", class: "guidance" %>
    <%= f.text_field :title, autofocus: true %>
  </p>

  <p>
    <%= f.label :text, "Story prompt", class: "guidance" %>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label :author, "Author credit", class: "guidance" %>
    <%= f.text_field :author, :value => (current_user.display_name if current_user) %>

  <p class="submit-submission">
    <%= f.submit @publish_now ? 'Create' : 'Submit', class: "submit-submission-button" %>
  </p>
<% end %>