config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get "today" => "days#today", as: "today"
  get "queue" => "days#queue", as: "queue"

  get "log_out" => "sessions#destroy", as: "log_out"
  get "log_in" => "sessions#new", as: "log_in"
  get "sign_up" => "users#new", as: "sign_up"

  get '/e/:id' => 'entries#find', as: 'find_entry'
  get '/stories/new' => 'submissions#new_story', as: 'new_story'

  root to: "home#index"
  get "archive" => "home#archive", as: "archive"
  get "about" => "home#about", as: "about"

  resources :days
  resources :users
  resources :sessions
  resources :entries

  resources :submissions do
    post '/assign' => 'submissions#assign', as: 'assign'
  end

  post '/create_and_publish' => 'submissions#create_and_publish', as: 'create_and_publish'

  resources :stories do
    post '/toggle_status' => 'stories#toggle_status', as: 'toggle_status'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Narratron</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <% [nil, 57, 72, 76, 114, 120, 144, 152].each do |size| %>
    <%= apple_touch_icon_tag(size) %>
  <% end %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, user-scalable=no">
</head>
<body id="<%= controller_slug %>">

<div id="banner">
  <h1 id="title"><%= link_to "Narratron", root_path %></h1>
  <p id="tag">Spin up a story.</p>

  <ul class="nav">
    <li><%= link_to "Today", today_path %>
    <li><%= link_to "Archives", archive_path %>
    <li><%= link_to "Submit Prompt", new_submission_path %>
    <% if current_user && (current_user.admin? || current_user.story_creator?) %>
      <li><%= link_to "Create Story", new_story_path %>
    <% end %>
    <% if current_user && current_user.admin? %>
      <li class="admin"><%= link_to "Submitted", submissions_path %>
      <li class="admin"><%= link_to "Queued", queue_path %>
    <% end %>
  </ul>

</div>

<div id="notifications">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
</div>

<div id="content">
  <%= yield %>
</div>

<hr class="faded" />

<div id="footer">
  <ul class="nav">
    <li><%= link_to "About", about_path %>
    <li><%= link_to "Site Updates", "http://narratron.tumblr.com/" %>
    <% if current_user %>
      <li><%= link_to "Your Profile", user_path(current_user) %>
      <li><%= link_to "Log Out", log_out_path %>
    <% else %>
      <li><%= link_to "Log In", log_in_path %>
    <% end %>
  </ul>
</div>

</body>
</html>